- id: sbt-fatal-warnings
  name: Scala fatal warnings
  stages: [commit,pre-push]
  language: python
  entry: sbt-fatal-warnings
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '4.0.0'
- id: sbt-unused-imports
  name: Scala unused imports (+ fatal warnings)
  stages: [commit,pre-push]
  language: python
  entry: sbt-fatal-warnings --add_arg='-Ywarn-unused-import'
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '4.0.0'
- id: sbt-scalafmt
  name: scalafmt formatting check
  stages: [commit,pre-push]
  language: python
  entry: sbt-scalafmt
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '4.0.0'
- id: sbt-wartremover
  name: Scala WartRemover plugin check
  language: python
  stages: [commit,pre-push]
  entry: sbt-wartremover
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '4.0.0'
